name: simple_video_player
description: A simple video player
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.1.12
  provider: ^5.0.0
  wakelock: ^0.5.0+2
  universal_html: ^2.0.8
  screen_brightness: ^0.0.4
  volume_controller: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.simple.video.simple_video_player
        pluginClass: SimpleVideoPlayerPlugin
      ios:
        pluginClass: SimpleVideoPlayerPlugin

